SET NAMES UTF8;

DROP DATABASE IF EXISTS damai;

CREATE DATABASE damai CHARSET=UTF8;

USE damai;
#创建表格
CREATE TABLE dm_login(
  did SMALLINT PRIMARY KEY AUTO_INCREMENT,
  dname VARCHAR(59) UNIQUE,
  dupwd VARCHAR(18),
  phone VARCHAR(30)
);
#插入数据
INSERT INTO dm_login VALUES(1,'sdf',123456,18122223333);


